### ISSUE TITLE
[Feature] Adding an option to preview word/sentences

### ISSUE THREAD

**Issue by wallace11** [7sDream/fontfor#2]
I know this is a little bit different from the original purpose of this, but I feel that with the ability to preview words/sentences this tool could become a great font previewer, much better than Gnome Specimen for example.

**Comment by 7sDream** [comment]
Yes, I also thinking of this feature many times, It's possible in theory.

You know, although our shell size is small then 120x50 in most of the time in daily usege, but with tui, It can be used as a 20x50 font list and a 200x200 canvas. 

If we want to clearly show the characteristics of a font, we need at least about 20x40, so we can have most 10x5=50 chars shown in canvas. If we add scroll, it can be more...

But, as you say, it's different from the original purpose. So, this feature is in my TODO list, but it won't come soon. 

I may extract some common code to a crate for render chars in tui and do some experiment before I start add this to fontfor tool.

**Comment by 7sDream** [comment]
This feature (if anyone need) should be provided by a separate tool, so closing this issue for now.
