### ISSUE TITLE
TUI as simple ... glyph render

### ISSUE THREAD

**Issue by xenoterracide** [7sDream/fontfor#54]
So having a problem in one terminal where it wasn't rendering "" but in another it was. Just a font "path" issue. Either way I found out I have lots of options. but --preview doesn't really tell me what I'm looking at, and neither does --tui. What I'd really like is for tui to just show me the character as it would appear in the terminal in that font (if possible). Even better would be to be able to see them all at once, like if using `--verbose` just show me it as it would appear in that font at that size.

**Comment by 7sDream** [comment]
Sorry for not noticing this issue two years ago 😢 

The character you provide is U+F015, which is in Unicode Private Use Area. Font designer can put anything in this glyph if the want, but normally no one do this, just let it empty.

So, some creative guys use those empty codepoint to draw useful thing they want show in text only enviroment(terminal, for example.). And eventually this grows up to a de-facto standard, named Nerd Fonts.

if you search F015 in [Nerd fonts cheat sheet](https://www.nerdfonts.com/cheat-sheet), you will get a "Home Icon". So if you have a patched nerd font(and configure it right), you can see this character in terminal.

---

And If I understand correctly, `--tui` should be the option you need. It will show all fonts that support this character, and how those fonts will display it, for example this is the result of my running:

![image](https://github.com/7sDream/fontfor/assets/7822577/15d680fb-59c7-4fbd-939e-ac34541b9eb4)
